#!/bin/bash

TRY_NUMBER=2
SPY3=python3
SPY2=python
CHATSERVER=/home/son/git/simplechat/chatserverd.py
OPTION="--port=9999"

LOADER=$SPY2

if [ "$1" = "PY3" ]; then
	LOADER=$SPY3
fi

function stopd() {
	old_pid=$(ps -o pid,cmd -e | grep -P "chatserverd" | grep -v grep | awk '{print $1}')

	if [ "$old_pid" ]; then
		printf "%-40s" "Stopping chatserverd with PID = $old_pid"
		/usr/bin/kill -s TERM $old_pid

		count=0

		while [ 1 ]
		do
			echo -n "."
			sleep 1
			pid=$(ps -o pid,cmd -e | grep -P "chatserverd" | grep -v grep | awk '{print $1}')
			
			if [ ! "$pid" ]; then
				if [ "$count" -ge "$TRY_NUMBER" ]; then
					echo " DONE     old PID = $old_pid"
					break
				fi
			else
				/usr/bin/kill -s TERM $old_pid
				count=-1
			fi
			
			count=$((count + 1))
		done
	fi
}

function startd() {
	printf "%-40s" "Starting chatserverd"
	$CHATSERVER $OPTION > /dev/null 2>&1

	count=0
	while [ 1 ]
	do
		echo -n "."
		sleep 1
		
		pid=$(ps -o pid,cmd -e | grep -P "chatserverd" | grep -v grep | awk '{print $1}')
		
		if [ "$pid" ]; then
			if [ "$count" -ge "$TRY_NUMBER" ]; then
				echo " OK       new PID = $pid"
				break
			fi
		else
			$CHATSERVER $OPTION > /dev/null 2>&1
			count=-1
		fi
		
		count=$((count + 1))
	done

	echo ""
	/usr/bin/eps chatserverd
}

function restart() {
	stopd
	startd
}

case "$1" in
	stop)
		stopd
		;;
	*)
		restart
esac
