#!/bin/bash

TRY_NUMBER=3

function stop() {
	old_pid=$(ps -o pid,cmd -e | grep supervisord.py | grep -v grep | awk '{print $1}')

	if [ "$old_pid" ]; then
		printf "%-40s" "Stopping supervisord with PID = $old_pid"
		/usr/bin/kill -s TERM $old_pid

		count=0

		while [ 1 ]
		do
			echo -n "."
			sleep 1
			pid=$(ps -o pid,cmd -e | grep supervisord.py | grep -v grep | awk '{print $1}')
			
			if [ ! "$pid" ]; then
				if [ "$count" -ge "$TRY_NUMBER" ]; then
					echo " DONE     old PID = $old_pid"
					break
				fi
			else
				/usr/bin/kill -s TERM $old_pid
				count=-1
			fi
			
			count=$((count + 1))
		done
	fi
}

function start() {
	printf "%-40s" "Starting supervisord"
	/home/son/Study/supervisor/supervisor/supervisord.py -c /home/son/local/etc/supervisord.conf

	count=0
	while [ 1 ]
	do
		echo -n "."
		sleep 1
		
		pid=$(ps -o pid,cmd -e | grep supervisord.py | grep -v grep | awk '{print $1}')
		
		if [ "$pid" ]; then
			if [ "$count" -ge "$TRY_NUMBER" ]; then
				echo " OK       new PID = $pid"
				break
			fi
		else
			/home/son/Study/supervisor/supervisor/supervisord.py -c /home/son/local/etc/supervisord.conf > /dev/null 2>&1
			count=-1
		fi
		
		count=$((count + 1))
	done

	echo ""
	/usr/bin/eps
}

function restart() {
	stop
	start
}

case "$1" in
	stop)
		stop
		;;
	*)
		restart
esac
